### ISSUE TITLE
Depend on setuptools >=16 for consistent exceptions

### ISSUE THREAD

**Issue by jayvdb** [pyupio/safety#35]
* safety version: 0.5.1 & master
* Python version: 3.4
* Operating System: Fedora 25

### Description

safety implicitly depends on setuptools, by way of `from setuptools import setup` in the `setup.py`, however `pkg_resources.parse_requirements` was [introduced](https://github.com/pypa/setuptools/commit/6d3753cc8d96814a) is only in setuptools 0.6, which is luckily just before [Ubuntu precise python-setuptools 0.6.24](http://packages.ubuntu.com/precise/python-setuptools) and [trusty python-setuptools 3.3](http://packages.ubuntu.com/trusty-updates/python-setuptools), but safety will very likely fail on anything earlier that Ubuntu precise (not a serious problem IMO, but .. worth painting the picture of this implicit requirement).

A more significant problem arises is when trying to catch requirements.txt parser errors, from `read_requirements`, the *ideal* exception to catch varies on the version of pkg_resources that is installed.  In all cases, `ValueError` is acceptable, however, as of setuptools 16 `RequirementParseError` was [introduced](https://github.com/pypa/setuptools/commit/cd79379c95051b94a7fa).

Given setuptools 16 is over 1.5 years ago, and safety is about keeping up to date, I suspect that adding setuptools >=16 will be acceptable.

### What I Did

```
try:
    safety.cli.read_requirements(text)
except pkg_resources.RequirementParseError:
    pass
```
Result:
```
AttributeError: 'module' object has no attribute 'RequirementParseError'
```

**Comment by jayfk** [comment]
Thanks, fixed in  b9551f1

**Comment by jayvdb** [comment]
just ftr, that commit doesnt solve the problem referred to here, but https://github.com/pyupio/safety/commit/f51f05b08842c9ce4322d05d644500dbb8458673 probably fixed it, and switching to `dparse` definitely did.
