### ISSUE TITLE
Running safety's test suite hijacks user's bashrc and leads to a broken system

### ISSUE THREAD

**Issue by mgorny** [pyupio/safety#766]
### Checklist

- [x] I agree to the terms within the [Safety Code of Conduct](https://github.com/pyupio/safety/blob/main/CODE_OF_CONDUCT.md).

### Safety version

03e057bb3567b101bb5764a9a8488d524c9393b7

### Python version

Python 3.13.5

### Operating System

Gentoo Linux amd64

### Describe the problem you'd like to have solved

I was running the safety's test suite in a virtual environment while working on #765. Afterwards, I've discovered that I can no longer use `uv` or `pip`:

```console
$ uv
bash: safety: command not found
$ pip
bash: safety: command not found
```

It is clear that safety has added itself to my `~/.bashrc` without my consent and without actually being installed:

```bash
# >>> Safety >>>
[ -f "/home/mgorny/.safety/.safety_profile" ] && . "/home/mgorny/.safety/.safety_profile"
# <<< Safety <<<
```

Said file hijacks all common Python package managers, therefore leading to an effectively broken system unless one is experienced enough to figure out where the problem is introduced and undo it.

### Describe the ideal solution

The test suite should run in full isolation, and not alter the user's system.

### What I Did

Included in the "problem" section.

**Comment by yeisonvargasf** [comment]
Hi @mgorny, Thanks for bringing this up, I sincerely apologize - this should never have happened.

**Immediate fix for your system:**

Remove these lines from your ~/.bashrc:

```
# >>> Safety >>>
[ -f "/home/mgorny/.safety/.safety_profile" ] && . "/home/mgorny/.safety/.safety_profile"
# <<< Safety <<<
```

This is a bug in our test isolation. I'll push a quick patch to run in isolation tomorrow while we work on the planned long-term fix (moving to containerized CLI e2e tests).

Thank you for catching this and for contributing to the project.

**Comment by yeisonvargasf** [comment]
This has been fixed in #767. Tests now run in isolated temporary directories to prevent system modification.

Thanks for catching this and reporting it. I'm going to close this, but please feel free to re-open if you encounter any issues.

**Comment by mgorny** [comment]
Thank you!

**Comment by mgorny** [comment]
Hmm, I'm afraid this isn't 100% fixed. As of f1e3d4de4733e6f182210cc7ee1752be3930852f, I'm still seeing one test attempt to modify my bashrc:

```pytb
$ pytest -nauto

[20] Main Dependencies:
------------------------------------------------------------
Package              Specification             Installed      
------------------------------------------------------------
Authlib              Authlib>=1.2.0            1.6.0          
click                Click>=8.0.2,<8.2.0       8.1.8          
dparse               dparse>=0.6.4             0.6.4          
filelock             filelock~=3.16.1          3.16.1         
httpx                httpx                     0.28.1         
Jinja2               jinja2>=3.1.0             3.1.6          
marshmallow          marshmallow>=3.15.0       4.0.0          
nltk                 nltk>=3.9                 3.9.1          
packaging            packaging>=21.0           25.0           
psutil               psutil~=6.1.0             6.1.1          
pydantic             pydantic>=2.6.0,<2.10.0   2.9.2          
requests             requests                  2.32.4         
ruamel.yaml          ruamel.yaml>=0.17.21      0.18.14        
safety-schemas       safety-schemas==0.0.14    0.0.14         
setuptools           setuptools>=65.5.1        80.9.0         
tenacity             tenacity                  9.1.2          
tomlkit              tomlkit                   0.13.3         
typer                typer>=0.12.1             0.16.0         
typing_extensions    typing-extensions>=4.7.1  4.14.0         

[29] Other Dependencies:
--------------------------------------------------------------------------------
annotated-types 0.7.0, anyio 4.9.0, certifi 2025.6.15, cffi 1.17.1
charset-normalizer 3.4.2, cryptography 45.0.4, execnet 2.1.1, h11 0.16.0
httpcore 1.0.9, idna 3.10, iniconfig 2.1.0, joblib 1.5.1
markdown-it-py 3.0.0, MarkupSafe 3.0.2, mdurl 0.1.2, pluggy 1.6.0
pycparser 2.22, pydantic_core 2.23.4, Pygments 2.19.2, pytest 8.4.1
pytest-xdist 3.7.0, regex 2024.11.6, rich 14.0.0, ruamel.yaml.clib 0.2.12
safety 3.5.2, shellingham 1.5.4, sniffio 1.3.1, tqdm 4.67.1, urllib3 2.5.0
========================================================= test session starts =========================================================
platform linux -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0
rootdir: /tmp/safety
configfile: pyproject.toml
plugins: xdist-3.7.0, anyio-4.9.0
6 workers [202 items]   
.....................................s......................................................................................... [ 62%]
........s.........................................................F........                                                     [100%]
============================================================== FAILURES ===============================================================
___________________________________________________ TestSafetyCLI.test_init_project ___________________________________________________
[gw3] linux -- Python 3.13.5 /tmp/safety/.venv/bin/python3

self = <tests.test_cli.TestSafetyCLI testMethod=test_init_project>
args = (<MagicMock name='SafetyCLI' id='139798794343760'>, <MagicMock name='project' id='139798794343424'>, <MagicMock name='...347120'>, <MagicMock name='is_valid' id='139798794347456'>, <MagicMock name='get_auth_info' id='139798794347792'>, ...)
test_console = <console width=135 None>
required_sections = ['Welcome to Safety, the AI-powered Software Supply Chain Firewall', 'Set Up Package Firewall', 'Secure Your First Codebase', 'Wrap Up', 'Next steps:', 'Configured pip’s global index', ...]
test_cases = [(False, ['Welcome to Safety, the AI-powered Software Supply Chain Firewall', 'Set Up Package Firewall', 'Secure Your ...steps:', 'Configured pip’s global index', ...], 0), (True, ['Do you want to continue with Firewall installation?'], 1)]

    @patch("safety.auth.utils.get_config_setting", return_value=None)
    @patch("safety.auth.cli.get_auth_info", return_value={"email": "test@test.com"})
    @patch.object(Auth, "is_valid", return_value=True)
    @patch(
        "safety.auth.utils.SafetyAuthSession.get_authentication_type",
        return_value=AuthenticationType.TOKEN,
    )
    @patch(
        "safety.auth.utils.SafetyAuthSession.check_project",
        return_value={"user_confirm": True},
    )
    @patch("safety.auth.utils.SafetyAuthSession.project", return_value={"slug": "slug"})
    @patch(
        "safety.auth.cli_utils.SafetyCLI",
        return_value=SafetyCLI(platform_enabled=True, firewall_enabled=True),
    )
    def test_init_project(self, *args):
        # Workarounds
        from safety.console import main_console as test_console
    
        required_sections = [
            "Welcome to Safety, the AI-powered Software Supply Chain Firewall",
            "Set Up Package Firewall",
            "Secure Your First Codebase",
            "Wrap Up",
            "Next steps:",
            "Configured pip’s global index",
            "Aliased pip to safety",
            "Pip, Poetry and Uv configured and secured",
        ]
    
        test_cases = [
            (False, required_sections, 0),
            (True, ["Do you want to continue with Firewall installation?"], 1),
        ]
    
        for interactive, outputs, exit_code in test_cases:
            with self.subTest(outputs=outputs, exit_code=exit_code):
                with patch(
                    "safety.cli.console", new=test_console
                ) as t_console, tempfile.TemporaryDirectory() as tempdir:
                    t_console.is_interactive = interactive
                    result = self.runner.invoke(self.cli, ["init", tempdir])
                    cleaned_stdout = click.unstyle(result.stdout)
                    assert result.exit_code == exit_code, (
                        f"CLI exited with non-zero exit code {result.exit_code}"
                    )
                    for section in outputs:
>                       assert section in cleaned_stdout, (
                            f"Required section '{section}' not found in output"
                        )
E                       AssertionError: Required section 'Aliased pip to safety' not found in output
E                       assert 'Aliased pip to safety' in "\n\nWelcome to Safety, the AI-powered Software Supply Chain Firewall.\n\n\nSafety is designed to:\n1. Work with your ...                                                 \n\n(Don't forget to run `source ~/.safety/.safety_profile` now!)\n\n"

tests/test_cli.py:808: AssertionError
---------------------------------------------------------- Captured log call ----------------------------------------------------------
ERROR    safety.init.main:main.py:365 Unable to load data on the init command
Traceback (most recent call last):
  File "/tmp/safety/safety/init/main.py", line 363, in launch_auth_if_needed
    data = ctx.obj.auth.client.initialize()
  File "/tmp/safety/.venv/lib/python3.13/site-packages/tenacity/__init__.py", line 338, in wrapped_f
    return copy(f, *args, **kw)
  File "/tmp/safety/.venv/lib/python3.13/site-packages/tenacity/__init__.py", line 477, in __call__
    do = self.iter(retry_state=retry_state)
  File "/tmp/safety/.venv/lib/python3.13/site-packages/tenacity/__init__.py", line 378, in iter
    result = action(retry_state)
  File "/tmp/safety/.venv/lib/python3.13/site-packages/tenacity/__init__.py", line 400, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/tmp/safety/.venv/lib/python3.13/site-packages/tenacity/__init__.py", line 480, in __call__
    result = fn(*args, **kwargs)
  File "/tmp/safety/safety/auth/utils.py", line 172, in wrapper
    raise SafetyError(message=reason, error_code=error_code)
safety.errors.SafetyError: Unable to find reason.
ERROR    safety.tool.interceptors.unix:unix.py:150 Failed to batch install aliases
Traceback (most recent call last):
  File "/tmp/safety/safety/tool/interceptors/unix.py", line 145, in _batch_install_tools
    self._ensure_source_line_in_user_rc()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/tmp/safety/safety/tool/interceptors/unix.py", line 112, in _ensure_source_line_in_user_rc
    with open(user_rc_path, "a") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/home/mgorny/.bashrc'
========================================================== warnings summary ===========================================================
.venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:291: 30 warnings
  /tmp/safety/.venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)

tests/test_cli.py::TestSafetyCLI::test_announcements_if_is_not_tty
tests/test_cli.py::TestSafetyCLI::test_check_vulnerabilities_found_default
  /tmp/safety/safety/safety.py:1853: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
    import pkg_resources

tests/test_cli.py: 1 warning
tests/test_safety.py: 13 warnings
  /usr/lib/python3.13/json/encoder.py:261: PydanticDeprecatedSince20: `pydantic_encoder` is deprecated, use `pydantic_core.to_jsonable_python` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
    return _iterencode(o, 0)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================= short test summary info =======================================================
FAILED tests/test_cli.py::TestSafetyCLI::test_init_project - AssertionError: Required section 'Aliased pip to safety' not found in output
======================================= 1 failed, 199 passed, 2 skipped, 46 warnings in 22.88s ========================================
```

**Comment by mgorny** [comment]
They seem to still edit `~/.config/pip/pip.conf` too.
